### ISSUE TITLE
additional area metrics

### ISSUE THREAD

**Issue by arpy0** [ianh/omsim#6]
perhaps this should be two issues, but:

- glyph area, or the area taken up at cycle 0, before any instructions are executed

- operational area, or the area that, once a rate is established for a solution, the area covered by a solution's progress over one looping point (ignoring any previously touched area).  due to area not always being constant, this might need to be a list like lexicographical cycles where it returns the area after several loops, or perhaps another alternative

**Comment by ianh** [comment]
I believe this has been resolved with `product 0 area` and `steady state area` / `per repetition area` / `per repetition^2 area`.

**Comment by ianh** [comment]
Fixed in 45064c9.
